#!name=B612Vip
#!desc=Remove Ads and Unlock VIP 
#!url=https://raw.githubusercontent.com/ahtungko/rules/main/module/b612.module

[Script]
b612 = type=http-response, pattern=^https?:\/\/user-b612-api.snow.me\/v1\/(purchase\/subscription\/subscriber\/status|purchase\/item\/user\/info), script-path=https://raw.githubusercontent.com/ahtungko/rules/main/script/b612/b612.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% user-b612-api.snow.me,content-b612-api.snow.me